// GameContext.js - 共有状態オブジェクト
// index.html 内の関数群が共有するグローバル変数をまとめたコンテキスト
export const ctx = {
    scene: null,
    camera: null,
    renderer: null,
    cars: [],
    currentCarIndex: 0,
    carPath: null,
    detailedPathPoints: null,
    roadWidth: 16,
    roadGroup: null,
    floor: null,
    gameTime: 5.0,
    timeSpeed: 0.01,
    isNight: false,
    isNightMode: false,
    cameraMode: 3,
    debugMode: false,
    weatherSystem: null,
    renderCache: null,
    raceManager: null,
    timeModeState: null,
    directionalLight: null,
    ambientLight: null,
    // 関数参照（モジュール間の循環依存を避けるためコンテキスト経由で登録）
    createCars: null,
    updateButtonActiveState: null,
    // 天気関連
    weatherApiKey: '2416f36c5b6368d2de6d3016e34ae8f8',
    currentTemperature: null,
    currentWindSpeed: null,
    currentHumidity: null,
    currentPressure: null,
    currentLocationName: null,
    // オート切替用
    lastCameraChangeTime: 0,
    cameraChangeInterval: 30000,
    availableCameraModes: [0, 1, 2, 3, 4, 5],
    lastCarChangeTime: 0,
    carChangeInterval: 20000,
    // フレーム
    currentFrameTime: 0,
    HORIZONTAL_SCALE: 100,
    VERTICAL_SCALE: 4,
};
